export type AtlasRow = {
  name: string;
  family: string;
  live: boolean;
  usedFor: string;
  whenAtWork: string;
};

export const ATLAS: AtlasRow[] = [
  {
    name: "Amazon S3",
    family: "Storage",
    live: true,
    usedFor: "Private site origin (OAC), inbox uploads (7-day expiry), Terraform state.",
    whenAtWork: "Default object store for assets, backups, data lakes.",
  },
  {
    name: "Amazon CloudFront",
    family: "Networking",
    live: true,
    usedFor: "HTTPS, cache, default cert. Shield Standard is on automatically.",
    whenAtWork: "Put a CDN in front of any internet-facing content.",
  },
  {
    name: "AWS Lambda (arm64)",
    family: "Compute",
    live: true,
    usedFor: "HTTP API, SQS worker, upload metadata, Cognito pre sign-up. Scale to zero.",
    whenAtWork: "Event-driven work; not a 24/7 app server.",
  },
  {
    name: "Amazon API Gateway HTTP API",
    family: "Networking",
    live: true,
    usedFor: "Routes, CORS, JWT authorizer on POST /quiz, access logs, throttle 10 rps.",
    whenAtWork: "Public HTTPS front door for Lambdas. REST API if you need API keys/WAF-style extras.",
  },
  {
    name: "Amazon DynamoDB",
    family: "Database",
    live: true,
    usedFor: "Single table: counter, jobs, uploads, quiz scores. On-demand billing.",
    whenAtWork: "Low-latency key-value at any scale; not SQL joins.",
  },
  {
    name: "Amazon SQS + DLQ",
    family: "Integration",
    live: true,
    usedFor: "Message Relay. maxReceiveCount 3 then dead-letter queue.",
    whenAtWork: "Decouple producers from workers; absorb spikes.",
  },
  {
    name: "Amazon EventBridge",
    family: "Integration",
    live: true,
    usedFor: "S3 Object Created → upload Lambda.",
    whenAtWork: "Bus between many AWS services without hard-wiring each pair.",
  },
  {
    name: "Amazon Cognito User Pool",
    family: "Security",
    live: true,
    usedFor: "Email/password. IdToken for POST /quiz. Not an Identity Pool (no AWS keys in the browser).",
    whenAtWork: "Customer identity. Use Hosted UI + PKCE in production apps.",
  },
  {
    name: "Amazon SNS",
    family: "Integration",
    live: true,
    usedFor: "Alarm email when the jobs DLQ is not empty. Confirm the subscription.",
    whenAtWork: "Fan-out: email, SMS, Lambda, HTTPS. We did not build a public contact form.",
  },
  {
    name: "IAM + STS + GitHub OIDC",
    family: "Security",
    live: true,
    usedFor: "GitHub assumes aether-lab-github-actions with a 2026 immutable sub claim. No AKIA in GitHub.",
    whenAtWork: "Default for CI into AWS. Least-privilege roles, short credentials.",
  },
  {
    name: "Amazon CloudWatch",
    family: "Ops",
    live: true,
    usedFor: "7-day logs, dashboard aether-lab, DLQ and worker-error alarms.",
    whenAtWork: "Metrics, logs, alarms for every production account.",
  },
  {
    name: "AWS X-Ray",
    family: "Ops",
    live: true,
    usedFor: "Active tracing on counter, worker, upload Lambdas.",
    whenAtWork: "Follow one request across services when logs are not enough.",
  },
  {
    name: "AWS Budgets",
    family: "Cost",
    live: true,
    usedFor: "$1 and $5 email alerts from Step 1 (console, not live Terraform).",
    whenAtWork: "Every account needs a budget before the first experimental cluster.",
  },
  {
    name: "Amazon EC2",
    family: "Compute",
    live: false,
    usedFor: "Not in this lab.",
    whenAtWork: "Always-on VMs, Windows, special software. Idle EC2 would blow a $5/month budget.",
  },
  {
    name: "NAT Gateway",
    family: "Networking",
    live: false,
    usedFor: "Not in this lab.",
    whenAtWork: "Private subnets that must reach the internet. Roughly tens of dollars/month idle — refused here.",
  },
  {
    name: "Application Load Balancer",
    family: "Networking",
    live: false,
    usedFor: "Not in this lab. HTTP API is the front door.",
    whenAtWork: "HTTP(S) to ECS/EC2/EKS. Hourly charge even with no traffic.",
  },
  {
    name: "Amazon RDS / Aurora",
    family: "Database",
    live: false,
    usedFor: "Not in this lab. DynamoDB covers key-value.",
    whenAtWork: "Relational data, transactions, SQL. Needs a subnet, backups, patching.",
  },
  {
    name: "Amazon EKS",
    family: "Compute",
    live: false,
    usedFor: "Not in this lab.",
    whenAtWork: "Many microservices, Kubernetes skills on the team. Control plane cost before a single pod.",
  },
  {
    name: "Amazon ECS / Fargate",
    family: "Compute",
    live: false,
    usedFor: "Not in this lab.",
    whenAtWork: "Containers without managing EC2. Still more moving parts than Lambda for this size.",
  },
  {
    name: "AWS WAF",
    family: "Security",
    live: false,
    usedFor: "Not in this lab. API throttle is the cheap guardrail.",
    whenAtWork: "OWASP rules, rate limits, bot control in front of CloudFront or ALB. WebACL has a monthly floor.",
  },
  {
    name: "Customer-managed KMS keys",
    family: "Security",
    live: false,
    usedFor: "Not in this lab. S3 uses SSE-S3 (AES256).",
    whenAtWork: "When compliance needs key rotation and CloudTrail on every decrypt. CMKs have a monthly fee.",
  },
  {
    name: "AWS Secrets Manager",
    family: "Security",
    live: false,
    usedFor: "Not in this lab. No long-lived DB passwords.",
    whenAtWork: "Rotate RDS/API secrets. Per-secret monthly cost — SSM Parameter Store is cheaper for simple values.",
  },
  {
    name: "Amazon ElastiCache / OpenSearch",
    family: "Database",
    live: false,
    usedFor: "Not in this lab. CloudFront caches static files.",
    whenAtWork: "Sub-millisecond session cache, or full-text search. Nodes idle-bill.",
  },
  {
    name: "Amazon GuardDuty / Bedrock",
    family: "Security / AI",
    live: false,
    usedFor: "Not in this lab.",
    whenAtWork: "GuardDuty: threat findings on CloudTrail/VPC/S3. Bedrock: managed FMs when the product needs AI, not for a resume counter.",
  },
  {
    name: "AWS CodePipeline",
    family: "DevOps",
    live: false,
    usedFor: "Not in this lab. GitHub Actions + OIDC instead.",
    whenAtWork: "All-in on AWS-native CI. Either is valid; we already live on GitHub.",
  },
];